<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    <NoWarn>$(NoWarn);1573;1591</NoWarn>
    
    <IsPackable>true</IsPackable>
    <PackageId>Toxic.GrandId.Sdk</PackageId>
    <Version>1.0.0</Version>
    <Company>Toxic Interactive Solutions</Company>
    <PackageTags>BankID;GrandID</PackageTags>
    <Description>A GrandID (Svensk e-identitet) API implementation.</Description>
    <RepositoryUrl>https://github.com/toxicinteractive/toxic-grandid-sdk</RepositoryUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <None Include="../../README.md" Pack="true" PackagePath="/" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.11" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="10.0.11" />
  </ItemGroup>
</Project>
